version: '3.7'

services:
  backend:
    container_name: iot-backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    network_mode: "host"
    
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    network_mode: "host"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config:/mqt-broker/config:rw

#   chromadb: 
#     container_name: iot-project-chromadb
#     build:
#       context: chromadb
#       dockerfile: Dockerfile
#     volumes:
#       - ./chromadb:/chromadb
#       - index_data:/index_data
#     environment:
#       - IS_PERSISTENT=TRUE
#     network_mode: "host"
#     ports:
#       - 8000:8000
# volumes:
#   index_data:
#     driver: local
