version: '3.7'

services:
  backend:
    container_name: iot-backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    network_mode: "host"
    
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    network_mode: "host"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config:/mqt-broker/config:rw