version: '3.7'

services:
  backend:
    container_name: iot-backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - iot-project-network

networks:
  iot-project-network:
    driver: bridge